import { Employer } from '@/generated/prisma';
import {
  AuthorizedPersonResponseDto,
  CreateAuthorizedPersonDto,
  UpdateAuthorizedPersonDto,
  NestedAuthorizedPersonDto,
} from './employerAuthorizedPerson.dto';
import {
  CreateProjectRequestDto,
  UpdateProjectRequestDto,
  ProjectRequestResponseDto,
  ReviewProjectRequestDto,
} from './employerProjectRequest.dto';
import {
  StatusHistoryResponseDto,
  VerifyEmployerDto,
  RejectEmployerDto,
} from './employerStatusHistory.dto';

// Re-export for backward compatibility
export {
  CreateAuthorizedPersonDto,
  UpdateAuthorizedPersonDto,
  AuthorizedPersonResponseDto,
  NestedAuthorizedPersonDto,
} from './employerAuthorizedPerson.dto';
export {
  CreateProjectRequestDto,
  UpdateProjectRequestDto,
  ProjectRequestResponseDto,
  ReviewProjectRequestDto,
} from './employerProjectRequest.dto';
export {
  StatusHistoryResponseDto,
  VerifyEmployerDto,
  RejectEmployerDto,
} from './employerStatusHistory.dto';

// Backward compatibility aliases (old names -> new names)
export type CreateAuthorizedPersonRequest = CreateAuthorizedPersonDto;
export type UpdateAuthorizedPersonRequest = UpdateAuthorizedPersonDto;
export type CreateProjectRequestRequest = CreateProjectRequestDto;
export type UpdateProjectRequestRequest = UpdateProjectRequestDto;
export type ReviewProjectRequestRequest = ReviewProjectRequestDto;
export type VerifyEmployerRequest = VerifyEmployerDto;
export type RejectEmployerRequest = RejectEmployerDto;

/**
 * Auto-generated fields that shouldn't be in create/update DTOs
 */
type AutoGeneratedFields =
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'verifiedAt'
  | 'lastLogin'
  | 'deletedAt';

/**
 * System-managed fields that shouldn't be directly updated
 */
type SystemManagedFields =
  | 'employerCode'
  | 'passwordHash'
  | 'verifiedByProfileId'
  | 'deletedByProfileId';

/**
 * DTO for creating a new employer
 */
export type CreateEmployerDto = Partial<Omit<Employer, AutoGeneratedFields | SystemManagedFields>> & {
  companyName: string;
};

/**
 * DTO for updating employer
 */
export type UpdateEmployerDto = Partial<Omit<Employer, AutoGeneratedFields | SystemManagedFields>>;

/**
 * DTO for employer response (excludes passwordHash)
 */
export type EmployerResponseDto = Omit<Employer, 'passwordHash'>;

/**
 * DTO for employer list (summary view)
 */
export type EmployerListDto = Pick<
  Employer,
  | 'id'
  | 'employerCode'
  | 'companyName'
  | 'clientName'
  | 'email'
  | 'phone'
  | 'isActive'
  | 'isVerified'
  | 'status'
  | 'createdAt'
>;

/**
 * DTO for employer detail view with relations
 */
export interface EmployerDetailDto extends EmployerResponseDto {
  authorizedPersons?: AuthorizedPersonResponseDto[];
  projectRequests?: ProjectRequestResponseDto[];
  projects?: any[];
  statusHistory?: StatusHistoryResponseDto[];
  verifiedByProfile?: {
    id: string;
    firstName: string | null;
    lastName: string | null;
  } | null;
}

/**
 * Query parameters for listing employers
 */
export interface EmployerListQuery {
  page?: number;
  limit?: number;
  search?: string;
  isActive?: boolean;
  isVerified?: boolean;
  status?: string;
}

/**
 * Response types
 */
export interface EmployerResponse {
  success: boolean;
  message: string;
  data?: EmployerResponseDto | EmployerDetailDto;
}

export interface EmployerListResponse {
  success: boolean;
  data: EmployerListDto[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

/**
 * DTO for importing employer with project requests (CSV import)
 */
export interface ImportEmployerDto {
  companyName: string;
  clientName?: string;
  email?: string;
  password?: string;
  phone?: string;
  altPhone?: string;
  registeredAddress?: string;
  companyRegistrationNumber?: string;
  gstNumber?: string;
  city?: string;
  district?: string;
  state?: string;
  landmark?: string;
  postalCode?: string;
  logoUrl?: string;
  // Project Request fields (optional)
  projectTitle?: string;
  projectDescription?: string;
  location?: string;
  estimatedStartDate?: string;
  estimatedDurationDays?: string;
  estimatedBudget?: string;
  additionalNotes?: string;
}

/**
 * DTO for export employer with project requests (CSV export)
 */
export interface ExportEmployerDto {
  employerCode: string;
  companyName: string;
  clientName: string;
  email: string;
  phone: string;
  altPhone: string;
  registeredAddress: string;
  companyRegistrationNumber: string;
  gstNumber: string;
  city: string;
  district: string;
  state: string;
  landmark: string;
  postalCode: string;
  logoUrl: string;
  isActive: string;
  isVerified: string;
  verifiedAt: string;
  createdAt: string;
  projectTitle: string;
  projectDescription: string;
  location: string;
  estimatedStartDate: string;
  estimatedDurationDays: string;
  estimatedBudget: string;
  additionalNotes: string;
  projectRequestStatus: string;
  projectRequestCreatedAt: string;
}

/**
 * Import options
 */
export interface ImportEmployerOptions {
  skipDuplicates?: boolean;
  updateExisting?: boolean;
}

/**
 * Import result for single row
 */
export interface ImportEmployerResult {
  rowNumber: number;
  success: boolean;
  employerId?: string;
  employerCode?: string;
  errors?: string[];
  warnings?: string[];
}

/**
 * Bulk import response
 */
export interface ImportEmployersResponse {
  totalRows: number;
  successCount: number;
  failureCount: number;
  results: ImportEmployerResult[];
}

/**
 * Nested project for unified employer creation
 */
export interface NestedProjectDto {
  name: string;
  location?: string;
  contactPhone?: string;
  description?: string;
  poCoNumber?: string;
  deploymentDate?: string;
  awardDate?: string;
  startDate?: string;
  endDate?: string;
  revisedCompletionDate?: string;
  status?: string;
  projectManagerProfileId?: string;
  isActive?: boolean;
  isAccommodationProvided?: boolean;
}

/**
 * Request body for creating employer with nested project in a single call
 */
export interface CreateEmployerWithProjectDto {
  // Employer fields
  companyName: string;
  clientName?: string;
  email?: string;
  phone?: string;
  altPhone?: string;
  registeredAddress?: string;
  companyRegistrationNumber?: string;
  gstNumber?: string;
  logoUrl?: string;
  isActive?: boolean;
  status?: string;
  city?: string;
  district?: string;
  state?: string;
  landmark?: string;
  postalCode?: string;
  // Nested entities
  authorizedPersons?: CreateAuthorizedPersonDto[];
  project?: NestedProjectDto;
}

/**
 * Response for unified employer creation with nested entities
 */
export interface CreateEmployerWithProjectResponse {
  employer: EmployerResponseDto;
  authorizedPersons?: AuthorizedPersonResponseDto[];
  project?: any;
}

/**
 * Request body for updating employer with authorized persons in a single call
 */
export interface UpdateEmployerWithAuthorizedPersonsDto {
  // Employer fields to update
  companyName?: string;
  clientName?: string;
  email?: string;
  phone?: string;
  altPhone?: string;
  registeredAddress?: string;
  companyRegistrationNumber?: string;
  gstNumber?: string;
  logoUrl?: string;
  isActive?: boolean;
  status?: string;
  city?: string;
  district?: string;
  state?: string;
  landmark?: string;
  postalCode?: string;
  // Nested authorized persons
  authorizedPersons?: NestedAuthorizedPersonDto[];
}

/**
 * Response for unified employer update with nested entities
 */
export interface UpdateEmployerWithAuthorizedPersonsResponse {
  employer: EmployerDetailDto;
  authorizedPersons: AuthorizedPersonResponseDto[];
}

/**
 * Request for employer self-registration with project request
 */
export interface RegisterEmployerDto {
  // Employer fields
  companyName: string;
  clientName?: string;
  email: string;
  password: string;
  phone?: string;
  altPhone?: string;
  registeredAddress?: string;
  companyRegistrationNumber?: string;
  gstNumber?: string;
  city?: string;
  district?: string;
  state?: string;
  landmark?: string;
  postalCode?: string;
  // Authorized person fields
  authorizedPersonName: string;
  authorizedPersonDesignation: string;
  authorizedPersonEmail: string;
  authorizedPersonContact: string;
  authorizedPersonAddress?: string;
  // Project request fields
  projectName: string;
  projectDescription: string;
  siteAddress: string;
  estimatedStartDate?: string;
  estimatedDurationDays?: number;
  estimatedBudget?: number;
  additionalNotes?: string;
  // Worker requirements
  workerRequirements: {
    category: string;
    count: number;
    notes?: string;
  }[];
}

// Backward compatibility aliases for employer types
export type CreateEmployerRequest = CreateEmployerDto;
export type UpdateEmployerRequest = UpdateEmployerDto;
export type CreateEmployerWithProjectRequest = CreateEmployerWithProjectDto;
export type UpdateEmployerWithAuthorizedPersonsRequest = UpdateEmployerWithAuthorizedPersonsDto;
export type RegisterEmployerRequest = RegisterEmployerDto;
export type NestedAuthorizedPersonRequest = NestedAuthorizedPersonDto;
export type NestedProjectRequest = NestedProjectDto;
