import { TrainingBatch } from '@/generated/prisma';

type AutoGeneratedFields = 'id' | 'createdAt' | 'updatedAt';

export interface TrainingBatchListDto {
  id: string;
  code: string | null;
  name: string | null;
  programName: string | null;
  provider: string | null;
  startDate: Date | null;
  endDate: Date | null;
  maxCapacity: number | null;
  status: string | null;
  location: string | null;
  createdAt: Date | null;
  _count?: {
    enrollments: number;
  };
}

// Flattened trainer object for API response
export interface TrainerInfo {
  id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  employeeCode: string | null;
  shift: string | null;
}

export interface TrainingBatchDetailDto extends Omit<TrainingBatch, never> {
  enrollments?: any[];
  // Flattened trainer object (or null if no trainer assigned)
  trainers?: TrainerInfo | null;
  createdBy?: {
    id: string;
    firstName: string | null;
    lastName: string | null;
  } | null;
  createdByProfile?: {
    id: string;
    firstName: string | null;
    lastName: string | null;
  } | null;
  _count?: {
    enrollments: number;
  };
}

export interface CreateTrainingBatchRequest {
  code?: string;
  name: string;
  programName?: string;
  program_name?: string; // Frontend sends snake_case
  provider?: string;
  startDate?: Date | string;
  start_date?: string; // Frontend sends snake_case
  endDate?: Date | string;
  end_date?: string; // Frontend sends snake_case
  durationDays?: number;
  maxCapacity?: number;
  max_capacity?: number; // Frontend sends snake_case
  status?: string;
  location?: string;
  description?: string;
  shift?: string;
  trainer_id?: string; // Trainer profile ID to assign
}

export interface UpdateTrainingBatchRequest {
  code?: string;
  name?: string;
  programName?: string;
  provider?: string;
  startDate?: Date;
  endDate?: Date;
  durationDays?: number;
  maxCapacity?: number;
  status?: string;
  location?: string;
  description?: string;
  shift?: string;
}

export interface TrainingBatchListQuery {
  page?: number;
  limit?: number;
  search?: string;
  status?: string;
  provider?: string;
}

// Enrollment DTOs
export interface CreateEnrollmentRequest {
  profileId: string;
  notes?: string;
  isCustomSchedule?: boolean;
  actualStartDate?: Date;
  actualEndDate?: Date;
}

export interface UpdateEnrollmentRequest {
  status?: string;
  notes?: string;
  isCustomSchedule?: boolean;
  actualStartDate?: Date;
  actualEndDate?: Date;
}

export interface CompleteEnrollmentRequest {
  notes?: string;
  forceComplete?: boolean;
  forceCompletionReason?: string;
}

export interface DropEnrollmentRequest {
  dropReason: string;
  droppedBeforeStart?: boolean;
}

// Trainer DTOs
export interface AssignTrainerRequest {
  trainerProfileId: string;
  shift: 'shift_1' | 'shift_2';
}
