/**
 * Central Prisma type re-exports
 * Re-exports Prisma generated types with cleaner naming conventions
 */

export type {
  activity_logs as ActivityLog,
  addresses as Address,
  bank_accounts as BankAccount,
  batch_enrollments as BatchEnrollment,
  blogs as Blog,
  certificates as Certificate,
  documents as Document,
  document_categories as DocumentCategory,
  employers as Employer,
  employer_authorized_persons as EmployerAuthorizedPerson,
  interactions as Interaction,
  interaction_types as InteractionType,
  news_updates as NewsUpdate,
  profiles as Profile,
  profile_blacklist as ProfileBlacklist,
  profile_skills as ProfileSkill,
  projects as Project,
  project_financials as ProjectFinancials,
  project_requests as ProjectRequest,
  project_request_requirements as ProjectRequestRequirement,
  project_resource_requirements as ProjectResourceRequirement,
  project_status_documents as ProjectStatusDocument,
  project_status_history as ProjectStatusHistory,
  project_worker_assignments as ProjectWorkerAssignment,
  qualifications as Qualification,
  qualification_types as QualificationType,
  roles as Role,
  role_permissions as RolePermission,
  scraper_websites as ScraperWebsite,
  skill_categories as SkillCategory,
  social_media_platform_posts as SocialMediaPlatformPost,
  social_media_posts as SocialMediaPost,
  stage_transitions as StageTransition,
  trainers as Trainer,
  training_batches as TrainingBatch,
  users as User,
} from '@/generated/prisma';
